/**
 * Danh mục mã lỗi toàn hệ thống — mọi exception nghiệp vụ phải đi kèm 1 code ở đây
 * thay vì chỉ có message tự do, để Frontend switch/case theo `code` thay vì so message.
 */
export const ErrorCode = {
  // Organization (ORGANIZATION_xxx) — SPEC-ORG-001
  ORGANIZATION_NOT_FOUND: 'ORGANIZATION_001',
  ORGANIZATION_SLUG_CONFLICT: 'ORGANIZATION_002',
  ORGANIZATION_TAXCODE_CONFLICT: 'ORGANIZATION_003',
  ORGANIZATION_EMAIL_CONFLICT: 'ORGANIZATION_004',
  ORGANIZATION_NOT_ACTIVE: 'ORGANIZATION_005',
  ORGANIZATION_OWNER_NOT_IN_ORGANIZATION: 'ORGANIZATION_006',
  ORGANIZATION_CONTEXT_FORBIDDEN: 'ORGANIZATION_007',
  ORGANIZATION_ARCHIVE_CONFIRMATION_MISMATCH: 'ORGANIZATION_008',

  // Branch (BRANCH_xxx) — SPEC-BRANCH-001
  BRANCH_NOT_FOUND: 'BRANCH_001',
  BRANCH_HAS_ACTIVE_WAREHOUSE: 'BRANCH_002',
  BRANCH_NOT_ACTIVE: 'BRANCH_003',
  BRANCH_INVOICE_PREFIX_CONFLICT: 'BRANCH_004',
  BRANCH_ORGANIZATION_MIN_ONE_ACTIVE: 'BRANCH_005',

  // Auth (AUTH_xxx)
  AUTH_INVALID_CREDENTIALS: 'AUTH_001',
  AUTH_ACCOUNT_NOT_ACTIVE: 'AUTH_002',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_003',
  AUTH_REFRESH_TOKEN_REUSED: 'AUTH_004',
  AUTH_REFRESH_TOKEN_EXPIRED: 'AUTH_005',
  AUTH_PERMISSION_VERSION_MISMATCH: 'AUTH_006',
  AUTH_TENANT_NOT_FOUND: 'AUTH_007',

  // RBAC (RBAC_xxx)
  RBAC_ROLE_NOT_FOUND: 'RBAC_001',
  RBAC_ROLE_CODE_CONFLICT: 'RBAC_002',
  RBAC_PERMISSION_CODE_INVALID: 'RBAC_003',
  RBAC_MISSING_PERMISSION: 'RBAC_004',

  // OTP / Forgot Password (OTP_xxx)
  OTP_RATE_LIMIT_EXCEEDED: 'OTP_001',
  OTP_INVALID_OR_EXPIRED: 'OTP_002',
  OTP_INCORRECT: 'OTP_003',
  OTP_MAX_ATTEMPTS_EXCEEDED: 'OTP_004',
  OTP_NOT_VERIFIED: 'OTP_005',
  OTP_COOLDOWN_ACTIVE: 'OTP_006',
  OTP_ACCOUNT_NOT_FOUND: 'OTP_007',

  // Product (PRODUCT_xxx)
  PRODUCT_NOT_FOUND: 'PRODUCT_001',
  PRODUCT_DUPLICATE: 'PRODUCT_002',
  PRODUCT_SKU_CONFLICT: 'PRODUCT_003',
  PRODUCT_BARCODE_CONFLICT: 'PRODUCT_004',
  PRODUCT_NOT_DELETED: 'PRODUCT_005',
  PRODUCT_ALREADY_DELETED: 'PRODUCT_006',
  PRODUCT_MISSING_RETAIL_PRICE: 'PRODUCT_007',

  // Category (CATEGORY_xxx)
  CATEGORY_NOT_FOUND: 'CATEGORY_001',
  CATEGORY_DUPLICATE: 'CATEGORY_002',
  CATEGORY_NOT_DELETED: 'CATEGORY_003',
  CATEGORY_HAS_PRODUCTS: 'CATEGORY_004',
  CATEGORY_CIRCULAR_REFERENCE: 'CATEGORY_005',
  CATEGORY_PARENT_NOT_FOUND: 'CATEGORY_006',

  // Brand (BRAND_xxx)
  BRAND_NOT_FOUND: 'BRAND_001',
  BRAND_DUPLICATE: 'BRAND_002',
  BRAND_HAS_PRODUCTS: 'BRAND_003',

  // Unit (UNIT_xxx)
  UNIT_NOT_FOUND: 'UNIT_001',
  UNIT_DUPLICATE: 'UNIT_002',
  UNIT_IN_USE: 'UNIT_003',

  // Barcode (BARCODE_xxx)
  BARCODE_NOT_FOUND: 'BARCODE_001',
  BARCODE_DUPLICATE: 'BARCODE_002',
  BARCODE_PRODUCT_NOT_FOUND: 'BARCODE_003',

  // Warehouse (WAREHOUSE_xxx)
  WAREHOUSE_NOT_FOUND: 'WAREHOUSE_001',
  WAREHOUSE_DUPLICATE: 'WAREHOUSE_002',
  WAREHOUSE_NOT_DELETED: 'WAREHOUSE_003',
  WAREHOUSE_HAS_STOCK_OR_TRANSACTIONS: 'WAREHOUSE_004',

  // Transfer (TRANSFER_xxx)
  TRANSFER_NOT_FOUND: 'TRANSFER_001',
  TRANSFER_SAME_WAREHOUSE: 'TRANSFER_002',
  TRANSFER_EMPTY_ITEMS: 'TRANSFER_003',
  TRANSFER_INVALID_STATUS_TRANSITION: 'TRANSFER_004',
  TRANSFER_DUPLICATE: 'TRANSFER_005',

  // Stock Count (STOCK_COUNT_xxx)
  STOCK_COUNT_NOT_FOUND: 'STOCK_COUNT_001',
  STOCK_COUNT_DUPLICATE: 'STOCK_COUNT_002',
  STOCK_COUNT_EMPTY_ITEMS: 'STOCK_COUNT_003',
  STOCK_COUNT_INVALID_STATUS_TRANSITION: 'STOCK_COUNT_004',
  STOCK_COUNT_ITEM_MISMATCH: 'STOCK_COUNT_005',

  // Inventory Adjustment (INVENTORY_ADJUSTMENT_xxx)
  INVENTORY_ADJUSTMENT_NOT_FOUND: 'INVENTORY_ADJUSTMENT_001',
  INVENTORY_ADJUSTMENT_DUPLICATE: 'INVENTORY_ADJUSTMENT_002',
  INVENTORY_ADJUSTMENT_EMPTY_ITEMS: 'INVENTORY_ADJUSTMENT_003',
  INVENTORY_ADJUSTMENT_INVALID_STATUS_TRANSITION: 'INVENTORY_ADJUSTMENT_004',
  INVENTORY_ADJUSTMENT_ITEM_MISMATCH: 'INVENTORY_ADJUSTMENT_005',
  INVENTORY_ADJUSTMENT_NEGATIVE_STOCK_NOT_ALLOWED: 'INVENTORY_ADJUSTMENT_006',

  // Supplier (SUPPLIER_xxx)
  SUPPLIER_NOT_FOUND: 'SUPPLIER_001',
  SUPPLIER_DUPLICATE: 'SUPPLIER_002',
  SUPPLIER_NOT_DELETED: 'SUPPLIER_003',
  SUPPLIER_HAS_PURCHASE_ORDERS: 'SUPPLIER_004',
  SUPPLIER_IMPORT_INVALID_FILE: 'SUPPLIER_005',
  SUPPLIER_IMPORT_VALIDATION_FAILED: 'SUPPLIER_006',
  SUPPLIER_PRODUCT_NOT_FOUND: 'SUPPLIER_007',
  SUPPLIER_PRODUCT_DUPLICATE: 'SUPPLIER_008',

  // Purchase Order (PURCHASE_ORDER_xxx)
  PURCHASE_ORDER_NOT_FOUND: 'PURCHASE_ORDER_001',
  PURCHASE_ORDER_DUPLICATE: 'PURCHASE_ORDER_002',
  PURCHASE_ORDER_INVALID_STATUS_TRANSITION: 'PURCHASE_ORDER_003',

  // Purchase Return (PURCHASE_RETURN_xxx)
  PURCHASE_RETURN_NOT_FOUND: 'PURCHASE_RETURN_001',
  PURCHASE_RETURN_DUPLICATE: 'PURCHASE_RETURN_002',
  PURCHASE_RETURN_INVALID_STATUS_TRANSITION: 'PURCHASE_RETURN_003',
  PURCHASE_RETURN_ORDER_NOT_RECEIVED: 'PURCHASE_RETURN_004',
  PURCHASE_RETURN_ITEM_NOT_IN_ORDER: 'PURCHASE_RETURN_005',
  PURCHASE_RETURN_EXCEEDS_RECEIVED: 'PURCHASE_RETURN_006',
  PURCHASE_RETURN_NEGATIVE_STOCK_NOT_ALLOWED: 'PURCHASE_RETURN_007',
  PURCHASE_RETURN_EMPTY_ITEMS: 'PURCHASE_RETURN_008',

  // Supplier Debt / Payment (SUPPLIER_DEBT_xxx)
  SUPPLIER_PAYMENT_EXCEEDS_BALANCE: 'SUPPLIER_DEBT_001',

  // Customer (CUSTOMER_xxx)
  CUSTOMER_NOT_FOUND: 'CUSTOMER_001',
  CUSTOMER_DUPLICATE: 'CUSTOMER_002',
  CUSTOMER_PHONE_DUPLICATE: 'CUSTOMER_003',
  CUSTOMER_NOT_DELETED: 'CUSTOMER_004',

  // Customer Point (CUSTOMER_POINT_xxx)
  CUSTOMER_POINT_INSUFFICIENT_BALANCE: 'CUSTOMER_POINT_001',

  // Cart (CART_xxx)
  CART_PRODUCT_NOT_FOUND: 'CART_001',
  CART_PRODUCT_NOT_SELLABLE: 'CART_002',
  CART_ITEM_NOT_FOUND: 'CART_003',

  // Payment (PAYMENT_xxx)
  PAYMENT_NOT_FOUND: 'PAYMENT_001',

  // Invoice (INVOICE_xxx)
  INVOICE_NOT_FOUND: 'INVOICE_001',

  // Checkout (CHECKOUT_xxx)
  CHECKOUT_EMPTY_CART: 'CHECKOUT_001',
  CHECKOUT_INSUFFICIENT_STOCK: 'CHECKOUT_002',
  CHECKOUT_INVENTORY_CONFLICT: 'CHECKOUT_003',
  CHECKOUT_VOUCHER_INVALID: 'CHECKOUT_004',
  CHECKOUT_POINTS_EXCEED_TOTAL: 'CHECKOUT_005',
  CHECKOUT_VOUCHER_CONFLICT: 'CHECKOUT_006',

  // Generic (dùng khi exception không tự gắn code cụ thể)
  VALIDATION_FAILED: 'VALIDATION_001',
  NOT_FOUND: 'HTTP_404',
  FORBIDDEN: 'HTTP_403',
  UNAUTHORIZED: 'HTTP_401',
  CONFLICT: 'HTTP_409',
  TOO_MANY_REQUESTS: 'HTTP_429',
  INTERNAL_SERVER_ERROR: 'HTTP_500',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
